[workspace]
authors = ["Jeanne Matheron <jeanne.matheron@inria.fr>"]
channels = ["conda-forge"]
name = "merge-queue-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=9.1.1,<10"
